#! /usr/bin/bash

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

chmod +x Miniconda3-latest-Linux-x86_64.sh

./Miniconda3-latest-Linux-x86_64.sh

rm ./Miniconda3-latest-Linux-x86_64.sh

conda env create -f environment.yml

